name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout repo
          uses: actions/checkout@v4
          
          
        - name: Welcome msg
          run: | 
            echo "My frst Actions"
            ls -ltra
            cat README.md

        - name: install cowsay program
          run: sudo apt-get install cowsay -y    

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, Im a dragon" >> dragon.txt  
          
        - name : search for file
          run: grep -i dragon dragon.txt  

        - name: display the file contents
          run: cat dragon.txt  





        - name: Checkout Repo  
          uses: actions/checkout@v4

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md
