name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome msg
          run: echo "My frst Actions"

        - name: Checkout Repo  
          uses: actions/checkout@v4

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md
