name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome msg
          run: | 
            echo "My frst Actions"
            ls -ltra
            cat README.md

        - name: install cowsay program
          run: sudo apt get install cowsay -y    

        - name: Generate ASCII Artwork
          run: cowsay -f lion "Run for cover, Im a Lion" >> lion.txt  
          
        - name : search for file
          run: grep -i lion lion.txt  

        - name: display the file contents
          run: cat lion.txt  





        - name: Checkout Repo  
          uses: actions/checkout@v4

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md
