name: Auto Label

on:
  issues:
    types: [opened]   #isuue opened

permissions:
  issues: write
  

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            if (context.payload.issue.title.includes('bug')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['bug']
              });
            }
