name: Composite action

on: workflow_dispatch

jobs:
    Composite:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout repo
             uses: actions/checkout@v4

           - name: Composite action cache
             uses: ./.github/workflows/custom-actions/npm-action
             with:
                path-of-folder: node_modules

