name: Multiple_jobs

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install cowsay
              run: sudo apt-get install cowsay -y


            - name: Execute cowsay command
              run: cowsay -f dragon "Im a Dragon" >> dragon.txt
              
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: dragon-artifact
                path: dragon.txt
                

            - name: sleep for 30 secs
              run: sleep 30

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: sleep for 10 secs
              run: sleep 10

            - name: downlaod artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon-artifact
         

            - name: test files exits 
              run: grep -i "dragon" dragon.txt  

    deploy:
        if: github.ref == 'refs/main/head'
        needs: test
        runs-on: ubuntuu-latest
        steps:

            - name: downlaod artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon-artifact

            - name: Read the file
              run: cat dragon.txt

            - name: Deploy
              run: echo deploying.........  
