name: Matrix_configuration

on:
    - workflow_dispatch 

jobs:  
     deploy:
        strategy:
            fail-fast: false
            max-parallel: 3
            matrix:
                os: [ubuntu-latest, ubuntu-20.04, windows-latest]
                images: [hello-world, alpine]
                exclude:
                  - images: alpine
                    os: windows-latest
                include:
                  - images: alpine
                    os: ubuntu-20.04
        runs-on: ${{matrix.os}}
        steps:
            - name: echo docker details
              run: docker info
              
            - name: Run images ${{matrix.os}}  
              run: docker run ${{matrix.images}}  
        


    
